export const defaultErrors = {
  required: "Required",
  invalidFormData: "Something went wrong...",
  invalid: "Invalid value",
  tooLong: "Too long (max {{max}})",
  tooShort: "Too short (min {{min}})",
  tooBig: "Too big (max {{max}})",
  tooSmall: "Too small (min {{min}})",
  fileIsTooBig: "File is too big (max {{max}} MB)",
  unsupportedFormat: "Invalid format (accepted: {{formats}})",
  invalidDate: "Invalid date",
  dateTooEarly: "Date is too early (min: {{min}})",
  dateTooLate: "Date is too late (max: {{max}})",
  dateRangeInvalid: "Out of range",
  dateRangeNotEnd: "End date not found",
  nameAlreadyExists: "Already exists",
  passwordsDontMatch: "Passwords don't match",
  invalidEmail: "Invalid e-mail address",
  invalidPhone: "Invalid phone number",
  tooManyElements: "Too many elements (max: {{max}})",
  tooFewElements: "Too few elements (min: {{min}})",
};